version: "3.1"

services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html/
      - ./.env:/var/www/html/.env
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: contactdb
    ports:
      - "3306:3306"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
